language: bash
sudo: required

os:
    - linux

install:
  # Install a custom version of shellcheck instead of Travis CI's default
  - scversion="latest" # or "v0.4.7", or "latest"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-${scversion}.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-${scversion}/shellcheck" "$@"; }

script:
    - shellcheck pm mkpkg
    # Check for lines longer than 80 chars.
    - if grep '.\{81\}' pm; then (exit 1); else (exit 0); fi
    - if grep '.\{81\}' mkpkg; then (exit 1); else (exit 0); fi
