#!/bin/sh
# shellcheck disable=SC2154,SC2123 source=/dev/null
#
# mkpkg - package builder for kiss linux.

pkgfile_read() {
    # Read the pkgfile.
    [ -f pkgfile ] || die "pkgfile not found"

    # Unset PATH while checking pkgfile.
    old_PATH=$PATH
    PATH=

    . pkgfile || die "syntax error in pkgfile"

    [ -z "$name" ] &&    die "name not defined in pkgfile"
    [ -z "$version" ] && die "version not defined in pkgfile"

    type build >/dev/null || die "build() not found in pkgfile."
    PATH=$old_PATH
}

get_pkg() {
    mkdir -p build || die "couldn't create build dir."

    for src in $source; do
        [ -f "build/${src##*/}" ] && continue

        printf '%s\n' "=> downloading $src."
        wget "$src" -P build || die "failed to download $src"
    done

    # Check if there are source files.
    _() { [ "$1" != "build/*" ] && dir_items=$#; }; _ build/*

    [ -z "$dir_items" ] && die "no source files found"
}

die() {
    # Display an error message to stderr and exit with error 1.
    printf '%s\n' "error: $1" >&2
    exit 1
}

main() {
    pkgfile_read
    get_pkg
}

main "$@"
