#!/bin/sh
# shellcheck disable=SC2154,SC2123 source=/dev/null
#
# mkpkg - package builder for kiss linux.

pkgfile_read() {
    # Read the pkgfile.
    [ -f pkgfile ] || die "pkgfile not found"

    # Unset PATH while checking pkgfile.
    old_PATH=$PATH
    PATH=

    . pkgfile || die "syntax error in pkgfile"

    [ -z "$name" ] &&    die "name not defined in pkgfile"
    [ -z "$version" ] && die "version not defined in pkgfile"

    type build >/dev/null || die "build() not found in pkgfile."
    PATH=$old_PATH
}

download() {
    # TODO: Parse $1 and check if it's a url.
    printf '%s\n' "=> downloading $1."

    wget "$1" || err "failed to download $1"
}

dl_source() {
    for src in $source; do
        [ -e "$src" ] && continue

        download "$src"
    done
}

die() {
    # Display an error message to stderr and exit with error 1.
    printf '%s\n' "error: $1" >&2
    exit 1
}

main() {
    pkgfile_read
    dl_source
}

main "$@"
